version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: alsafa-app
    container_name: alsafa-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - alsafa-network

  db:
    image: mysql:8.0
    container_name: alsafa-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - alsafa-network

  nginx:
    image: nginx:alpine
    container_name: alsafa-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - alsafa-network

  redis:
    image: redis:alpine
    container_name: alsafa-redis
    restart: unless-stopped
    networks:
      - alsafa-network

networks:
  alsafa-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
